version: "3.9"

services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d 
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - backend
    ports:
      - "4002:8080"

volumes:
  pgdata:

networks:
  backend:
